apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-neta
  namespace: neta-aviv-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: neta
