apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-neta
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: neta
  hostPath:
    path: /mnt/data/wordpress
